services:
  mysql:
    image: mariadb:11.4
    logging:
      driver: none
    command: [ "--max-allowed-packet=512M" ]
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: $SERVICE_PASSWORD_ROOT
      MYSQL_DATABASE: wordpress
      MYSQL_USER: $SERVICE_USER_WORDPRESS
      MYSQL_PASSWORD: $SERVICE_PASSWORD_WORDPRESS
    restart: always
    networks:
      - default
  litespeed:
    image: litespeedtech/openlitespeed:1.8.3-lsphp83
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./bin:/app/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    restart: always
    environment:
      TZ: $TimeZone
    networks:
      - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    # command: redis-server --requirepass 8b405f60665e48f795752e534d93b722
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge
